"""Initial migration with fixed column names

Revision ID: a5c19249ef40
Revises: 
Create Date: 2025-06-19 21:54:17.258268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c19249ef40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('total_mangoes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('ripeness_level', sa.String(length=20), nullable=True),
    sa.Column('bbox_xmin', sa.Integer(), nullable=True),
    sa.Column('bbox_xmax', sa.Integer(), nullable=True),
    sa.Column('bbox_ymin', sa.Integer(), nullable=True),
    sa.Column('bbox_ymax', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['histories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    op.drop_table('histories')
    # ### end Alembic commands ###
